[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pdo", "php83Extensions.pdo_sqlite", "php83Extensions.sqlite3", "php83Extensions.mbstring", "php83Extensions.dom", "php83Extensions.xml", "nodejs_20"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build",
    "touch database/database.sqlite",
    "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
